### ISSUE TITLE
Customize Introduction Panel

### ISSUE THREAD

**Issue by nicolasFernandez** [MatthewYork/iPhone-IntroductionTutorial#15]
Is there any way to customize introduction panel so you can use a "full screen" image? or display the description text on any location of the screen? So you can use it like a fake overlay introduction screen with screenshots of the application.

**Comment by MatthewYork** [comment]
See this pull request for more information. 
https://github.com/MatthewYork/iPhone-IntroductionTutorial/pull/14

I will be reviewing this new code soon and if all goes well, pulling it in to support some of the functionality you are requesting. As for full screen, there are no current plans to support it because of the necessary skip button and dots at the bottom. Perhaps in a future implementation...

**Comment by jacobjiangwei** [comment]
can you just simply give us a solution to done this like your intro_sample_image : https://github-camo.global.ssl.fastly.net/17651699f51374bed14fe7c4efa8b9295f070051/687474703a2f2f696d616765736861636b2e75732f612f696d673232312f383630362f696f7373696d756c61746f7273637265656e73686f746d2e706e67

Many many of our apps , just simply show the image with text , and with full screen , not scall our intro image to small one .

**Comment by MatthewYork** [comment]
This was done by adding a padding to the image. If you would like to recreate this look, take a look at https://raw.github.com/MatthewYork/iPhone-IntroductionTutorial/master/IntroductionExample/SampleImage1.png for a good example of how much spacing to leave around the edges.

Also, when things slow down, I will be writing a new version of this that is hopefully much more flexible.

**Comment by jacobjiangwei** [comment]
Is there an way to just give me a chance to diy ? such as give you just a full screen uiview ?
